apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgresql
        image: postgres:9.4
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
          #ports:
          #- containerPort: 80
      volumes:
      - name: db-data 
        emptyDir: {}
