apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
spec:
  selector:
    app.kubernetes.io/name: vote-deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 31000
  type: NodePort
