apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
  type: NodePort
